---
apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricFollowerChannel
metadata:
  name: demo-vikmsp
spec:
  anchorPeers:
    - host: vik-peer0.default
      port: 7051
    - host: vik-peer1.default
      port: 7051

  hlfIdentity:
    secretKey: user.yaml
    secretName: vik-admin
    secretNamespace: default
  mspId: vikMSP
  name: demo
  externalPeersToJoin: []
  orderers:
    - certificate: |
        -----BEGIN CERTIFICATE-----
        MIIC8zCCApqgAwIBAgIUdqgFGVr+YBGhNBoYvV+nWlpkzZIwCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjUxMTE3MjMyNDU4WhcNMjYxMTE4MjMyNjAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAElzEhQj76wbqPk+H366zDgLjxMi5OrTllJqO50mEHSnkB
        gkXRlXEPlfVPLrH8N8AFTaHt5TfUPDjJGb+VDjEcjaOCAV8wggFbMA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQUwH3p1v+hwWOgvvaP6yAyyTMrIv8wKwYDVR0jBCQwIoAg
        7VJbuXtHuKOx/LUyvgrRXnoPkZP0FB/fP0wS0mhCDYIwcwYDVR0RBGwwaoIJbG9j
        YWxob3N0gglvcmQtbm9kZTGCEW9yZC1ub2RlMS5kZWZhdWx0ghRub2RlMS1vcmQu
        bG9jYWxoby5zdIIdYWRtaW4tb3JkZXJlcjEtb3JkLmxvY2FsaG8uc3SHBH8AAAGH
        BKwSAAIwWwYIKgMEBQYHCAEET3siYXR0cnMiOnsiaGYuQWZmaWxpYXRpb24iOiIi
        LCJoZi5FbnJvbGxtZW50SUQiOiJvcmRlcmVyIiwiaGYuVHlwZSI6Im9yZGVyZXIi
        fX0wCgYIKoZIzj0EAwIDRwAwRAIgfF5fMv0Xeyohvm1HNPfHwVNEA6kIrrJfnXeT
        DnCBgd4CICExBXSlDpnv6GxI7DINnBCpc9+xwCI+XbM4ZN/AiG7N
        -----END CERTIFICATE-----
      url: grpcs://ord-node1.default:7050

  peersToJoin:
    - name: vik-peer0
      namespace: default
    - name: vik-peer1
      namespace: default

