
name: hlf-network
version: 1.0.0
client:
  organization: ""
organizations:
  
  ordMSP:
    mspid: ordMSP
    cryptoPath: /tmp/cryptopath
    users: {}
    peers: []
    orderers:
      - ord-node0.default
      - ord-node1.default
      - ord-node2.default
      - ord-node3.default
  orgMSP:
    mspid: orgMSP
    cryptoPath: /tmp/cryptopath
    users:
      org-admin-default:
        cert:
          pem: |
            -----BEGIN CERTIFICATE-----
            MIICUjCCAfmgAwIBAgIUQRuxXZ0udgSmU2XI38oKplB7LMswCgYIKoZIzj0EAwIw
            ajELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
            YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEL
            MAkGA1UEAxMCY2EwHhcNMjUxMTE3MjAwMTM4WhcNMjYxMTE4MjAwMjAwWjAgMQ4w
            DAYDVQQLEwVhZG1pbjEOMAwGA1UEAxMFYWRtaW4wWTATBgcqhkjOPQIBBggqhkjO
            PQMBBwNCAAT8RhUwiY8i5NR00lUsVX1Vdy1fXZQ34wzEMA06Ty2ZGg31x4+yJGqa
            jyEFslv1uE2Mwr2ct51WeMcCtrIsALUgo4HGMIHDMA4GA1UdDwEB/wQEAwIHgDAM
            BgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTlqBrhItNlvuiRKsE4+Nky0zh/0TArBgNV
            HSMEJDAigCAHDHvaup+M5eC6Kv5yvj/FF+2eeya08vlOL7cx54CvYjBXBggqAwQF
            BgcIAQRLeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
            bnRJRCI6ImFkbWluIiwiaGYuVHlwZSI6ImFkbWluIn19MAoGCCqGSM49BAMCA0cA
            MEQCIF9q/ub5NX5R7ML3CZnfuCgIVOUx9JUWxPwU2hw7MCLdAiAoSwVcbbpMkDpM
            epkO3Y2+sDPwgZ984CwJXQamD73S9A==
            -----END CERTIFICATE-----
            
        key:
          pem: |
            -----BEGIN PRIVATE KEY-----
            MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg9fI1BLSU/Y82+jgL
            kOijiZnUIS1lGsQz2ruqI70DxlChRANCAAT8RhUwiY8i5NR00lUsVX1Vdy1fXZQ3
            4wzEMA06Ty2ZGg31x4+yJGqajyEFslv1uE2Mwr2ct51WeMcCtrIsALUg
            -----END PRIVATE KEY-----
            
    peers:
      - org-peer0.default
      - org-peer1.default
    orderers: []

orderers:
  ord-node0.default:

    url: grpcs://node0-ord.localho.st:443


    adminUrl: https://admin-orderer0-ord.localho.st:443
    adminTlsCert: |
        -----BEGIN CERTIFICATE-----
        MIIC9DCCApqgAwIBAgIUDVj/VLMgHRvxoDlgoEjez9PQh74wCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjUxMTE3MjAwMzE4WhcNMjYxMTE4MjAwNDAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAEqJMVO7Ye7BLyi8/yrV5p0YHmebrLrRNBptOIBXSLbuGE
        Ge1k7jnHMhIMV7h6QKVX/9GPkK6WHr+TC62O1Z3UE6OCAV8wggFbMA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQU94HddnLIFDWFN1pjNqbyBIrqGuUwKwYDVR0jBCQwIoAg
        yLsHuPkMEkMByvpp6Yul8Bpsftfx4MKA0/4WBuQ+UvYwcwYDVR0RBGwwaoIJbG9j
        YWxob3N0gglvcmQtbm9kZTCCEW9yZC1ub2RlMC5kZWZhdWx0ghRub2RlMC1vcmQu
        bG9jYWxoby5zdIIdYWRtaW4tb3JkZXJlcjAtb3JkLmxvY2FsaG8uc3SHBH8AAAGH
        BKwSAAIwWwYIKgMEBQYHCAEET3siYXR0cnMiOnsiaGYuQWZmaWxpYXRpb24iOiIi
        LCJoZi5FbnJvbGxtZW50SUQiOiJvcmRlcmVyIiwiaGYuVHlwZSI6Im9yZGVyZXIi
        fX0wCgYIKoZIzj0EAwIDSAAwRQIhAPSXkEGHErA1XE5Jo4DrHezKIT7XNO5lfQQ7
        xP0ixhJbAiBGpobOKPObIEzMfX7PT541vreXgp9zxP0A1f6WsZO5hg==
        -----END CERTIFICATE-----
        

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQd1c2pScK1ATiP9j8Q0bLdzAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNTExMTcyMDAzMThaFw0zNTExMTgyMDAzMThaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVR2hkbkuRdfv4zkj
        LPpgOZh1MjsC/wcm0IpXMezmfIL3vF70j/TnmGBH1HYhJJO/FI1KXW57olib5t4R
        Dk//UKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCDIuwe4+QwSQwHK+mnp
        i6XwGmx+1/HgwoDT/hYG5D5S9jAKBggqhkjOPQQDAgNJADBGAiEA5IqEuOja9vW+
        0bDOQ20KFk8T8K5jIbz+d+1StrnWQFQCIQD8Rv8whBacGsKUX3gHYujbBozKsiBk
        b+EyBFrFqgyi0g==
        -----END CERTIFICATE-----
        
  ord-node1.default:

    url: grpcs://node1-ord.localho.st:443


    adminUrl: https://admin-orderer1-ord.localho.st:443
    adminTlsCert: |
        -----BEGIN CERTIFICATE-----
        MIIC9DCCApqgAwIBAgIUNilbOjYsKrxdM2wg7R3e4+33gfMwCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjUxMTE3MjAwMzE4WhcNMjYxMTE4MjAwNDAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAEOfmY6V6cOOMpyEXrxzQueAXKwQaY4xLs5cgrFju2jX4b
        0ZMk+mLM1qRiEWTr9iUZ2mPdfGzD03TMroW9ZfcmTqOCAV8wggFbMA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQUul3Utry6mLQvq35O4EuSyEXKE0MwKwYDVR0jBCQwIoAg
        yLsHuPkMEkMByvpp6Yul8Bpsftfx4MKA0/4WBuQ+UvYwcwYDVR0RBGwwaoIJbG9j
        YWxob3N0gglvcmQtbm9kZTGCEW9yZC1ub2RlMS5kZWZhdWx0ghRub2RlMS1vcmQu
        bG9jYWxoby5zdIIdYWRtaW4tb3JkZXJlcjEtb3JkLmxvY2FsaG8uc3SHBH8AAAGH
        BKwSAAIwWwYIKgMEBQYHCAEET3siYXR0cnMiOnsiaGYuQWZmaWxpYXRpb24iOiIi
        LCJoZi5FbnJvbGxtZW50SUQiOiJvcmRlcmVyIiwiaGYuVHlwZSI6Im9yZGVyZXIi
        fX0wCgYIKoZIzj0EAwIDSAAwRQIhAPw9MYn9dbQEFaSXus1GbSKSvxrgD8wb9DXp
        dNLl/wPnAiALAzFszOmUlS42ODvfiWkyRCdUYYKZoRyeZ++EX5Dbsw==
        -----END CERTIFICATE-----
        

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQd1c2pScK1ATiP9j8Q0bLdzAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNTExMTcyMDAzMThaFw0zNTExMTgyMDAzMThaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVR2hkbkuRdfv4zkj
        LPpgOZh1MjsC/wcm0IpXMezmfIL3vF70j/TnmGBH1HYhJJO/FI1KXW57olib5t4R
        Dk//UKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCDIuwe4+QwSQwHK+mnp
        i6XwGmx+1/HgwoDT/hYG5D5S9jAKBggqhkjOPQQDAgNJADBGAiEA5IqEuOja9vW+
        0bDOQ20KFk8T8K5jIbz+d+1StrnWQFQCIQD8Rv8whBacGsKUX3gHYujbBozKsiBk
        b+EyBFrFqgyi0g==
        -----END CERTIFICATE-----
        
  ord-node2.default:

    url: grpcs://node2-ord.localho.st:443


    adminUrl: https://admin-orderer2-ord.localho.st:443
    adminTlsCert: |
        -----BEGIN CERTIFICATE-----
        MIIC8zCCApqgAwIBAgIUBgy/kcup+CFxNY2vUDYmQqiVtDUwCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjUxMTE3MjAwMzE4WhcNMjYxMTE4MjAwNDAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAEB7MGLEnSHBb7AVGVc8d0S6CZLxVAhTJs/R/NjdosIVOM
        2R6xpgMJAT+g8wy5WFdmkYVlBxWjEZdhC065qncqY6OCAV8wggFbMA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQU2N85xVviUGzhHFMPoddWiVvw/UowKwYDVR0jBCQwIoAg
        yLsHuPkMEkMByvpp6Yul8Bpsftfx4MKA0/4WBuQ+UvYwcwYDVR0RBGwwaoIJbG9j
        YWxob3N0gglvcmQtbm9kZTKCEW9yZC1ub2RlMi5kZWZhdWx0ghRub2RlMi1vcmQu
        bG9jYWxoby5zdIIdYWRtaW4tb3JkZXJlcjItb3JkLmxvY2FsaG8uc3SHBH8AAAGH
        BKwSAAIwWwYIKgMEBQYHCAEET3siYXR0cnMiOnsiaGYuQWZmaWxpYXRpb24iOiIi
        LCJoZi5FbnJvbGxtZW50SUQiOiJvcmRlcmVyIiwiaGYuVHlwZSI6Im9yZGVyZXIi
        fX0wCgYIKoZIzj0EAwIDRwAwRAIgP88SVXOFZuuHGDQODa+Hh6JaXuYlpbz1hbxb
        adHqcHsCIBvR7fKm8+4j7Deq031N5fD/YTgdMf8+/dYdh5ik8MlW
        -----END CERTIFICATE-----
        

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQd1c2pScK1ATiP9j8Q0bLdzAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNTExMTcyMDAzMThaFw0zNTExMTgyMDAzMThaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVR2hkbkuRdfv4zkj
        LPpgOZh1MjsC/wcm0IpXMezmfIL3vF70j/TnmGBH1HYhJJO/FI1KXW57olib5t4R
        Dk//UKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCDIuwe4+QwSQwHK+mnp
        i6XwGmx+1/HgwoDT/hYG5D5S9jAKBggqhkjOPQQDAgNJADBGAiEA5IqEuOja9vW+
        0bDOQ20KFk8T8K5jIbz+d+1StrnWQFQCIQD8Rv8whBacGsKUX3gHYujbBozKsiBk
        b+EyBFrFqgyi0g==
        -----END CERTIFICATE-----
        
  ord-node3.default:

    url: grpcs://node3-ord.localho.st:443


    adminUrl: https://admin-orderer3-ord.localho.st:443
    adminTlsCert: |
        -----BEGIN CERTIFICATE-----
        MIIC9DCCApqgAwIBAgIUIqLBf+DG4appoeTa3wDMFz28/GAwCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjUxMTE3MjAwMzE4WhcNMjYxMTE4MjAwNDAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAEs1sDY83hf+H08gC3D98j46ytwjtv6JNRKpDUns+guoYR
        Gc3Rs+80adjJyPRuXlDj4GgA4YQTWrlAVctlR+vmDKOCAV8wggFbMA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQUTm5ml3KcpZHYmKaoSa1Nl32KbukwKwYDVR0jBCQwIoAg
        yLsHuPkMEkMByvpp6Yul8Bpsftfx4MKA0/4WBuQ+UvYwcwYDVR0RBGwwaoIJbG9j
        YWxob3N0gglvcmQtbm9kZTOCEW9yZC1ub2RlMy5kZWZhdWx0ghRub2RlMy1vcmQu
        bG9jYWxoby5zdIIdYWRtaW4tb3JkZXJlcjMtb3JkLmxvY2FsaG8uc3SHBH8AAAGH
        BKwSAAIwWwYIKgMEBQYHCAEET3siYXR0cnMiOnsiaGYuQWZmaWxpYXRpb24iOiIi
        LCJoZi5FbnJvbGxtZW50SUQiOiJvcmRlcmVyIiwiaGYuVHlwZSI6Im9yZGVyZXIi
        fX0wCgYIKoZIzj0EAwIDSAAwRQIhAK2brcny0+4vFT0TmIZgdg51EgzhgGYl3+Lw
        PrRo9KYnAiAF8XTQjAWYq5HVJzchdE+5sAo96E1h04yX6iTEUgBXwA==
        -----END CERTIFICATE-----
        

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRjCCAeugAwIBAgIQd1c2pScK1ATiP9j8Q0bLdzAKBggqhkjOPQQDAjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTAeFw0yNTExMTcyMDAzMThaFw0zNTExMTgyMDAzMThaMG0xCzAJ
        BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx
        GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV
        BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVR2hkbkuRdfv4zkj
        LPpgOZh1MjsC/wcm0IpXMezmfIL3vF70j/TnmGBH1HYhJJO/FI1KXW57olib5t4R
        Dk//UKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
        BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCDIuwe4+QwSQwHK+mnp
        i6XwGmx+1/HgwoDT/hYG5D5S9jAKBggqhkjOPQQDAgNJADBGAiEA5IqEuOja9vW+
        0bDOQ20KFk8T8K5jIbz+d+1StrnWQFQCIQD8Rv8whBacGsKUX3gHYujbBozKsiBk
        b+EyBFrFqgyi0g==
        -----END CERTIFICATE-----
        


peers:
  org-peer0.default:

    url: grpcs://peer0-org.localho.st:443

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRzCCAeygAwIBAgIRAJxrLEEMduVczWA0rFPopu8wCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjUxMTE3MjAwMTM4WhcNMzUxMTE4MjAwMTM4WjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEUcDawEW1G2Ppma
        AiCwSw/JE+OjeJhm9NxgqGPp2eKhoCJczMtuI43caT/3iJnQbOcFvpeDdogFJaT6
        rXXfl0WjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg8A1wQabQjlKCqXnM
        dSi9KdbUL20d4DoYt1xUyYJSLgMwCgYIKoZIzj0EAwIDSQAwRgIhAI6V5wISnmSZ
        z1LUEJBXjW41oFKGMUQ/xUvk5j/+czOFAiEA6LcOC01byL/Q92sPwGXdcFsUXbxZ
        7fbKDdHnGKXPSUY=
        -----END CERTIFICATE-----
        
  org-peer1.default:

    url: grpcs://peer1-org.localho.st:443

    grpcOptions:
      allow-insecure: false
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICRzCCAeygAwIBAgIRAJxrLEEMduVczWA0rFPopu8wCgYIKoZIzj0EAwIwbTEL
        MAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGljYW50
        ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEOMAwG
        A1UEAxMFdGxzY2EwHhcNMjUxMTE3MjAwMTM4WhcNMzUxMTE4MjAwMTM4WjBtMQsw
        CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl
        MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD
        VQQDEwV0bHNjYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEUcDawEW1G2Ppma
        AiCwSw/JE+OjeJhm9NxgqGPp2eKhoCJczMtuI43caT/3iJnQbOcFvpeDdogFJaT6
        rXXfl0WjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYI
        KwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQg8A1wQabQjlKCqXnM
        dSi9KdbUL20d4DoYt1xUyYJSLgMwCgYIKoZIzj0EAwIDSQAwRgIhAI6V5wISnmSZ
        z1LUEJBXjW41oFKGMUQ/xUvk5j/+czOFAiEA6LcOC01byL/Q92sPwGXdcFsUXbxZ
        7fbKDdHnGKXPSUY=
        -----END CERTIFICATE-----
        
certificateAuthorities:
  
  ord-ca.default:

    url: https://ord-ca.localho.st:443


    registrar:
        enrollId: enroll
        enrollSecret: "enrollpw"

    caName: ca
    tlsCACerts:
      pem: 
       - |
            -----BEGIN CERTIFICATE-----
            MIICWjCCAf+gAwIBAgIRAIHACNGQzira7UF3PMjvZC8wCgYIKoZIzj0EAwIwUjET
            MBEGA1UEBhMKQ2FsaWZvcm5pYTEJMAcGA1UEBxMAMQkwBwYDVQQJEwAxFDASBgNV
            BAoTC0h5cGVybGVkZ2VyMQ8wDQYDVQQLEwZGYWJyaWMwHhcNMjUxMTE3MjAwMzE4
            WhcNMzUxMTE4MjAwMzE4WjBSMRMwEQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQH
            EwAxCTAHBgNVBAkTADEUMBIGA1UEChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZh
            YnJpYzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABEzqB/lZe02YekY0EVMw5Bcq
            7YMQU7Jrd/aZZV27zSrowA4LLVzyL4kYQ9h3j1na7ioQiO5bjm2zZmz4shU+ba+j
            gbUwgbIwDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
            BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCDUOtVfHdG7edL5Y8UdAQ0+
            PfggMdzb2IrTapIZxdhxUDBFBgNVHREEPjA8gglsb2NhbGhvc3SCBm9yZC1jYYIO
            b3JkLWNhLmRlZmF1bHSCEW9yZC1jYS5sb2NhbGhvLnN0hwR/AAABMAoGCCqGSM49
            BAMCA0kAMEYCIQDQJgjWfTOwla2B87QGKX1J40DZOWB3d7fd7p/8KkHunAIhALvt
            nYjdZ6VijuGoWcdr0NFGlUu8FDH3hpPNKALboIGS
            -----END CERTIFICATE-----
            
  
  org-ca.default:

    url: https://org-ca.localho.st:443


    registrar:
        enrollId: enroll
        enrollSecret: "enrollpw"

    caName: ca
    tlsCACerts:
      pem: 
       - |
            -----BEGIN CERTIFICATE-----
            MIICWDCCAf6gAwIBAgIQJInPqCLCAjPxSOlsmm/wuTAKBggqhkjOPQQDAjBSMRMw
            EQYDVQQGEwpDYWxpZm9ybmlhMQkwBwYDVQQHEwAxCTAHBgNVBAkTADEUMBIGA1UE
            ChMLSHlwZXJsZWRnZXIxDzANBgNVBAsTBkZhYnJpYzAeFw0yNTExMTcyMDAxMzha
            Fw0zNTExMTgyMDAxMzhaMFIxEzARBgNVBAYTCkNhbGlmb3JuaWExCTAHBgNVBAcT
            ADEJMAcGA1UECRMAMRQwEgYDVQQKEwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFi
            cmljMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEZhoEbud07E1IeI7sc0yWIV1F
            swbwg59JoQve8U4vvykdw/Y9FnUR5H8Z/T3qzH6ffJm1+UKs0DY/qJ3V99s0RaOB
            tTCBsjAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUF
            BwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIOaCxAlldxRIVwBS0nWzp3tE
            NPJ6hdkEwFxC72gH7CXTMEUGA1UdEQQ+MDyCCWxvY2FsaG9zdIIGb3JnLWNhgg5v
            cmctY2EuZGVmYXVsdIIRb3JnLWNhLmxvY2FsaG8uc3SHBH8AAAEwCgYIKoZIzj0E
            AwIDSAAwRQIgeSZvKtB3QRreVIsUVNmH/mYLeMtAEg6OW3FlQS/O6A8CIQCMieUO
            w5GmLvF3LWj+Yf16BYREstWOLl7CLbY9Y9g4EA==
            -----END CERTIFICATE-----
            


channels:
  demo:

    orderers:
      - ord-node0.default
      - ord-node1.default
      - ord-node2.default
      - ord-node3.default

    peers:
       org-peer0.default:
        discover: true
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
       org-peer1.default:
        discover: true
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

